const postPlaylist = (prompt, token, items) => {
  let songs = items.map(item => item.uri);
  let params = {
      "token": token,
      "playlist_name":prompt,
      "playlist_description": "Auto-generated by Spotif.ai",
      songs: songs,
  };
  console.log(JSON.stringify(params));
  let url = "http://localhost:8000/api/playlist"; 
  fetch(url, {
      method: 'POST',
      headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json',
      },
      body: JSON.stringify(params)
    })
    .then((res) => res.json())
    .then((res) => {
        console.log(res)
    })
    .catch((err) => {
        console.log(err);
    });
}

export default postPlaylist;